version: '3'

services:
  api_service:
    build: .
    container_name: asante_api_service
    ports:
      - "50051:50051"
    environment:
      - DB_HOST=asante-postgres
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=ASANTe@cu
    networks:
      - asante_network

  envoy_api:
    image: envoyproxy/envoy:v1.15.0
    container_name: envoy_api
    volumes:
      - ./envoy-api.yaml:/etc/envoy/envoy.yaml:ro
    ports:
      - "8081:8081"
    depends_on:
      - api_service
    networks:
      - asante_network

networks:
  asante_network:
    external: true
