version: '3'

services:
  ml_service:
    build: .
    container_name: asante_ml_service
    ports:
      - "50052:50052"
    environment:
      - DB_HOST=asante-postgres
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=ASANTe@cu
    networks:
      - asante_network

networks:
  asante_network:
    external: true